services:
  - type: web
    name: internhub-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://internhub_user:213064727@internhub-production.nka6k7e.mongodb.net/?retryWrites=true&w=majority&appName=internhub-production
      - key: MONGODB_DB_NAME
        value: internhub
      - key: PORT
        value: 10000

  - type: web
    name: internhub-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://internhub-backend.onrender.com